FROM chuanwen/cowsay:latest

ENTRYPOINT [ "/usr/games/cowsay" ]
# defino um entrypoint para a execução do comando

CMD ["#SOU BACK"]

## Fim!

# docker build -t xablau .
# docker run xablau (sairá a msg padrão do CMD)
# docker run xablau Muuuuuuuuuuuh (ele vai parametrizar o CMD)
# docker run xablau -f moofasa "#SOU BACK" (exibe um leão :o)
