FROM chuanwen/cowsay:latest

ENTRYPOINT ["usr/games/cowsay"]

CMD ["msg padrão :D"]

#Fim

# docker build -t cowsay

# docker run cowsay

## docker run cowsay Muuuuuuh

## docker run cowsay -f moofasa "#SOU BACK"